version: '3.8'

services:
  python-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-python-container
    volumes:
      - .:/usr/src/app
    networks:
      - my_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
    tty: true
  postgres:
    image: postgres:17-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres-data:  # Volume untuk data PostgreSQL

networks:
  my_network:
    driver: bridge